### ISSUE TITLE
Plugin does no longer modify the Slack app

### ISSUE THREAD

**Issue by mallowigi** [AtomMaterialUI/mtslack#106] opened 2021-11-11 14:18 UTC
Hi folks, 

This issue will serve as the last breath of the plugin, as since version 4.22.0 Slack finally decided to patch the option to add custom tweaks to their code, thus locking any personalization features. It makes sense, as allowing users to do so potentially allows people to inject malware code, which is a very serious security breach.

However, there is still a way to inject the themes manually via the Slack Dev Mode. Please read the README for more details.

**Comment by marshimaro** [comment] 2021-11-23 21:26
There is still a way to inject script into preload.bundle.js. The version 4.22 just has the checksum of sar files stored in plist for integrity check. You need to update that checksum after repacking sar files to pass the validation.

**Comment by mallowigi** [comment] 2021-11-23 21:29
I tried to modify the plist manually but it broke the application completely. Have you managed to do it?

**Comment by marshimaro** [comment] 2021-11-23 21:53
> I tried to modify the plist manually but it broke the application completely. Have you managed to do it?

Yes it worked for me. Here is what I did.

1. I am running Slack on Macbook Pro with Intel CPU so I will go update app-x64.sar. Assume another file app-arm64.sar is for the latest Macbook Pro with M1 chip. So just unpack, update and repack app-x64.sar as we did previously.
`$ pwd`
`/Applications/Slack.app/Contents/Resources`
`$ npx asar extract app-x64.asar app-x64.asar.unpacked`
`$ vi app-x64.asar.unpacked/dist/preload.bundle.js` /// inject my script for CSS customization
`$ npx asar pack app-x64.asar.unpacked app-x64.asar`

2. Run Slack in command line. It will be broken but the exception tells the old checksum and new checksum. 
`$ /Applications/Slack.app/Contents/Resources/MacOS/Slack`
`[5543:1123/130400.504181:FATAL:asar_util.cc(164)] Integrity check failed for asar archive (<old-checksum> vs <new-checksum>)`

3. update checksum. Assume it will update the following files.
`$pwd`
`/Applications/Slack.app/Contents`
`grep -r -l <old-checksum> .`
`./Frameworks/Slack Helper.app/Contents/Info.plist`
`./Frameworks/Slack Helper (Renderer).app/Contents/Info.plist`
`./Frameworks/Electron Framework.framework/Versions/A/Resources/Info.plist`
`./Frameworks/ReactiveObjC.framework/Versions/A/Resources/Info.plist`
`./Frameworks/Squirrel.framework/Versions/A/Resources/Info.plist`
`./Frameworks/Mantle.framework/Versions/A/Resources/Info.plist`
`./Frameworks/Slack Helper (Plugin).app/Contents/Info.plist`
`./Frameworks/Slack Helper (GPU).app/Contents/Info.plist`
`./Info.plist`
`$ grep -r -l <old-checksum> . | while read file; do sed -i '' 's/<old-checksum>/<new-checksum>/g' "$file"; done`

4. You should be able to run Slack normally then.

**Comment by elgorditosalsero** [comment] 2021-12-07 08:09
Hi,

So, basically, everytime we open slack, we have to run mtslack and paste the code, right?

I'm hating Slack right now 😠

**Comment by mallowigi** [comment] 2021-12-07 08:28
I've changed a bit the option, to now launch Slack in debug mode so you can open the dev tools out of the box. When I have time I'll investigate @marshimaro's workaround

**Comment by mallowigi** [comment] 2021-12-31 12:55
@marshimaro I tried to follow your instructions, but alas I can't make it work still:

```
grep -r -l eaa066e9cacd966cee76b33f9a95ace950024b16b8549c79e73b514a17b3cff0 . | while read file; do sudo sed -i '' 's/eaa066e9cacd966cee76b33f9a95ace950024b16b8549c79e73b514a17b3cff0/ab860cba9a3e8da17d821ddbc1ffa745bf1c9f966465cf35ecea6edfa145cc46/g' "$file"; done
```

however after having done that, Slack no longer launches, giving me the message `Illegal instruction: 4`

**Comment by marshimaro** [comment] 2022-01-03 19:28
> @marshimaro I tried to follow your instructions, but alas I can't make it work still:
> 
> ```
> grep -r -l eaa066e9cacd966cee76b33f9a95ace950024b16b8549c79e73b514a17b3cff0 . | while read file; do sudo sed -i '' 's/eaa066e9cacd966cee76b33f9a95ace950024b16b8549c79e73b514a17b3cff0/ab860cba9a3e8da17d821ddbc1ffa745bf1c9f966465cf35ecea6edfa145cc46/g' "$file"; done
> ```
> 
> however after having done that, Slack no longer launches, giving me the message `Illegal instruction: 4`

I didn't see this. The only drawback of above method to me so far is that Slack could not be opened after a reboot due to invalid signature. But it can be resolved by resigning the whole Slack app folder.

By the way, I am with Catalina 10.15.7.

**Comment by Saghen** [comment] 2022-03-08 23:07
It seems like this is a Mac specific issue since I wasn't able to reproduce on 4.24 on Windows or Manjaro

**Closed** 2024-09-27 18:56 UTC
